'use client';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, BarChart, Bar, ScatterChart, Scatter, Legend } from 'recharts';
import type { Rank, Cluster } from '@/lib/types';
const compact = (v: number) => new Intl.NumberFormat('id-ID', {notation: 'compact', maximumFractionDigits: 1}).format(v);
const colors = ['#17654b', '#ce963e', '#778aac', '#7f6b91', '#50a39d', '#c77053'];
export function TrendChart({data, unit}: {data: {year: number; value: number|null}[]; unit: string}) {
  return <div className="chart" role="img" aria-label={`Tren produksi tahunan dalam ${unit}; total observasi tersedia`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top: 20, left: 0, right: 20, bottom: 4}}><defs><linearGradient id="area-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3f8062" stopOpacity={.16}/><stop offset="100%" stopColor="#3f8062" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e8ece7" vertical={false} strokeDasharray="3 5"/><XAxis dataKey="year" axisLine={false} tickLine={false} tickMargin={14}/><YAxis tickFormatter={compact} axisLine={false} tickLine={false} width={65}/><Tooltip formatter={(v) => [Number(v).toLocaleString('id-ID') + ' ' + unit, 'Produksi']} contentStyle={{borderRadius: 10, borderColor: '#dce3db'}}/><Area type="linear" dataKey="value" stroke="#246c50" fill="url(#area-fill)" strokeWidth={2.5} dot={{r: 4, fill: '#fff', strokeWidth: 2}} connectNulls={false} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>;
}
export function RankChart({data, unit, all=false}: {data: Rank[]; unit: string; all?: boolean}) {
  return <div className="chart rank-chart" style={{height: Math.max(240, data.length * (all ? 34 : 43))}} role="img" aria-label={`Peringkat produksi dalam ${unit}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{top: 10, right: 28, bottom: 4, left: 0}}><CartesianGrid horizontal={false} stroke="#e8ece7" strokeDasharray="3 5"/><XAxis type="number" tickFormatter={compact} axisLine={false} tickLine={false}/><YAxis dataKey="name" type="category" width={150} axisLine={false} tickLine={false} tick={{fontSize: 11}}/><Tooltip formatter={(v) => [Number(v).toLocaleString('id-ID') + ' ' + unit, 'Produksi']} cursor={{fill: '#f3f6ef'}}/><Bar dataKey="value" fill="#55876a" radius={[0, 4, 4, 0]} barSize={16} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>;
}
export function ClusterChart({cluster}: {cluster: Cluster}) {
  return <div className="chart" role="img" aria-label="Scatter plot produksi dan diversifikasi komoditas menurut cluster"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{top: 20, right: 20, bottom: 25, left: 20}}><CartesianGrid strokeDasharray="3 5"/><XAxis type="number" dataKey="total_production" name="Produksi" unit={` ${cluster.unit}`} tickFormatter={compact} label={{value: `Produksi (${cluster.unit})`, position: 'bottom'}}/><YAxis type="number" dataKey="active_commodities" name="Komoditas aktif"/><Tooltip cursor={{strokeDasharray: '3 3'}}/><Legend verticalAlign="top"/>{cluster.clusters?.map(c => <Scatter key={c.id} name={c.name} data={cluster.points?.filter(p => p.cluster === c.id)} fill={colors[c.id % colors.length]} shape={c.id % 2 ? 'triangle' : 'circle'} isAnimationActive={false}/>)}</ScatterChart></ResponsiveContainer></div>;
}
