'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import { Sprout, LayoutDashboard, Table2, Database, Activity, Info, ArrowUpRight, ArrowDownRight, ChevronRight, RefreshCw, Download, Search, MapPin, Leaf, Layers3, Lightbulb, ShieldCheck, CircleHelp, SlidersHorizontal, ArrowRight, ExternalLink } from 'lucide-react';
import { apiUrl, remoteBackend } from '@/lib/api';
import type { Filters, Options, Status, Dashboard, Source, Observation, TableSource, Insight } from '@/lib/types';
const TrendChart = dynamic(() => import('./charts').then(m => m.TrendChart), {ssr:false});
const RankChart = dynamic(() => import('./charts').then(m => m.RankChart), {ssr:false});
const ClusterChart = dynamic(() => import('./charts').then(m => m.ClusterChart), {ssr:false});
const links = [{href:'/', mode:'dashboard', label:'Overview', icon:LayoutDashboard}, {href:'/data',mode:'data',label:'Data Explorer',icon:Table2},{href:'/sources',mode:'sources',label:'Data Sources',icon:Database},{href:'/diagnostics',mode:'diagnostics',label:'Diagnostics',icon:Activity},{href:'/about',mode:'about',label:'About the Project',icon:Info}];
const number = (v: number|null|undefined, digits=0) => v == null ? '—' : v.toLocaleString('id-ID', {maximumFractionDigits:digits});
const date = (v: string|null|undefined) => v ? new Date(v).toLocaleString('id-ID', {dateStyle:'medium',timeStyle:'short'}) : 'Belum disinkronkan';
async function get<T>(url: string, signal?: AbortSignal): Promise<T> { const response = await fetch(apiUrl(url), {signal}); if (!response.ok) throw new Error(`Data belum dapat diakses (${response.status}). Coba lagi setelah backend selesai aktif.`); return response.json(); }
function Sources({items}: {items: Source[]}) { return <details className="source-details"><summary><CircleHelp size={13}/> Sumber & metodologi</summary><p>BPS; analisis aplikasi. Nilai kosong tidak dianggap nol. Total menggunakan satuan yang sama dan hanya observasi tersedia.</p>{items.map((s,i) => <div key={i} className="source-item"><strong>{s.source_table_title}</strong><span>{s.source} · {s.year}</span><small>Diakses: {date(s.last_synced)} · ID: {s.source_table_id}</small>{s.source_url&&<a className="source-link" href={s.source_url} target="_blank" rel="noreferrer">Buka tabel asli BPS ↗</a>}</div>)}</details>; }
function Empty({text='Tidak ada observasi pada pilihan ini.'}: {text?: string}) { return <div className="empty"><Sprout size={28}/><strong>Data belum tersedia</strong><p>{text}</p></div>; }
function InsightCard({item}: {item: Insight}) { return <article className={`insight ${item.severity}`}><div className="insight-icon"><Lightbulb size={18}/></div><span className="eyebrow">{item.type.replace('_',' ')}</span><h3>{item.title}</h3><p>{item.message}</p><details><summary>Why this insight? <ChevronRight size={14}/></summary><dl className="evidence">{Object.entries(item.evidence).map(([key,value]) => <div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{typeof value === 'number' ? number(value,2) : Array.isArray(value) ? value.join(', ') : String(value ?? '—')}</dd></div>)}</dl><Sources items={item.provenance}/></details></article>; }

export default function Workspace({mode}: {mode:'dashboard'|'data'|'sources'|'diagnostics'|'about'}) {
  const [status,setStatus] = useState<Status|null>(null), [options,setOptions] = useState<Options|null>(null);
  const [filters,setFilters] = useState<Filters>({}), [dashboard,setDashboard] = useState<Dashboard|null>(null);
  const [error,setError] = useState(''), [loading,setLoading] = useState(true), [revision,setRevision] = useState(0);
  const [allDistricts,setAllDistricts] = useState(false), [search,setSearch] = useState(''), [page,setPage] = useState(1);
  const [sort,setSort] = useState('year'), [direction,setDirection] = useState('desc');
  const [data,setData] = useState<{rows:Observation[];total:number}|null>(null), [tables,setTables] = useState<TableSource[]>([]);
  const [refreshing,setRefreshing] = useState(false), [notice,setNotice] = useState('');
  useEffect(() => {const controller=new AbortController(); Promise.all([get<Status>('/api/bps/status',controller.signal),get<Options>('/api/agriculture/options',controller.signal)]).then(([s,o])=>{setStatus(s);setOptions(o);setFilters(f=>Object.keys(f).length ? f : {year:String(o.defaults.year ?? ''),unit:o.defaults.unit ?? ''});setError('');}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}}); return ()=>controller.abort();},[revision]);
  const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v)).toString();
  useEffect(()=>{if(!options)return;const controller=new AbortController();setLoading(true);setError('');
    const promise=mode==='dashboard' ? get<Dashboard>(`/api/agriculture/dashboard?${query}`,controller.signal).then(setDashboard)
      : mode==='data' ? get<{rows:Observation[];total:number}>(`/api/agriculture/data?${query}&search=${encodeURIComponent(search)}&page=${page}&sort=${sort}&direction=${direction}`,controller.signal).then(setData)
      : mode==='sources' ? get<{selected:TableSource[]}>('/api/bps/tables',controller.signal).then(v=>setTables(v.selected)) : Promise.resolve();
    promise.catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();
  },[options,query,mode,search,page,sort,direction]);
  useEffect(()=>{if(!refreshing && !status?.refreshing)return;const timer=setInterval(()=>{get<Status>('/api/bps/status').then(s=>{setStatus(s);if(!s.refreshing){setRefreshing(false);setRevision(v=>v+1);setNotice(s.error ? 'Refresh gagal. Cache valid sebelumnya dipertahankan.' : 'Sinkronisasi selesai.');}}).catch(e=>{setError(e.message);setRefreshing(false);});},2500);return()=>clearInterval(timer);},[refreshing,status?.refreshing]);
  async function refresh(){setRefreshing(true);setNotice('Sinkronisasi BPS berlangsung…');try{const res=await fetch(apiUrl('/api/bps/refresh'),{method:'POST',headers:{'Content-Type':'application/json'}});if(!res.ok)throw new Error('Sinkronisasi tidak dapat dimulai. Periksa Diagnostics.');}catch(e){setError((e as Error).message);setRefreshing(false);}}
  function change(key:string,value:string){setFilters(f=>({...f,[key]:value}));setPage(1);}
  const summary=dashboard?.summary, top=summary?.top_commodities[0], district=summary?.top_districts[0], unit=summary?.unit ?? '';
  const connection=status?.using_cache ? (remoteBackend ? 'Published BPS snapshot' : 'Cached Data') : status?.api_connected ? 'BPS API Connected' : 'BPS API Unavailable';
  return <div className="app-shell"><a className="skip-link" href="#content">Lewati navigasi</a><aside className="sidebar"><Link href="/" className="brand"><div className="brand-mark"><Sprout size={26}/></div><span>BOGOR<span>AGRI INTELLIGENCE</span></span></Link><div className="sidebar-caption">RESEARCH WORKSPACE</div><nav aria-label="Navigasi utama">{links.map(({href,mode:m,label,icon:Icon},i)=><Link key={href} href={href} className={`${m===mode?'active':''} ${i===2?'nav-divider':''}`} aria-current={m===mode?'page':undefined}><Icon size={18}/>{label}{m===mode&&<span className="active-dot"/>}</Link>)}</nav><div className="sidebar-bottom"><div className="region-label"><MapPin size={16}/><span>Kabupaten Bogor<small>Jawa Barat, Indonesia</small></span></div><div className="source-seal"><ShieldCheck size={18}/><p>Powered by official data<span>Badan Pusat Statistik</span></p></div><span className="version">PUBLIC DATA · OPEN INSIGHTS</span></div></aside>
  <div className="workspace"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={13}/><strong>{links.find(l=>l.mode===mode)?.label}</strong></div><span className={`connection ${status?.using_cache?'cached':''}`}><i/>{connection}</span></header><main id="content"><div className="api-notice"><p>Layanan ini menggunakan API Badan Pusat Statistik (BPS).</p><small>Aplikasi independen untuk riset dan portofolio nonkomersial. Tidak disponsori atau disahkan oleh BPS.</small></div><div className="page-heading"><div><div className="eyebrow"><span className="tiny-line"/> KABUPATEN BOGOR / AGRICULTURAL RESEARCH</div><h1>{mode==='dashboard'?'Bogor Agricultural Intelligence':mode==='data'?'Explore the data':mode==='sources'?'Official sources. Clear provenance.':mode==='diagnostics'?'Pipeline diagnostics':'From public data to understanding.'}</h1><p>{mode==='dashboard'?'Data-driven agricultural intelligence for Kabupaten Bogor':mode==='data'?'Telusuri observasi BPS yang sudah dinormalisasi, hingga ke sumbernya.':mode==='sources'?'Setiap angka berawal dari tabel resmi Badan Pusat Statistik.':mode==='diagnostics'?'Status autentikasi, penemuan tabel, dan kualitas data dalam satu tempat.':'Memahami pola produksi pertanian melalui data BPS dan analitik.'}</p></div>{mode!=='about'&&!remoteBackend&&<button className="button refresh" onClick={refresh} disabled={refreshing||status?.refreshing}><RefreshCw size={15} className={refreshing?'spin':''}/>{refreshing?'Syncing…':'Refresh data'}</button>}</div>
  <div aria-live="polite">{error&&<div className="alert error"><Info size={18}/>{error}<button onClick={()=>setRevision(v=>v+1)}>Coba lagi</button></div>}{notice&&<div className="notice">{notice}</div>}{status&&!status.api_key_configured&&!remoteBackend&&<div className="alert">BPS API key belum dikonfigurasi. Tambahkan BPS_API_KEY ke backend/.env.</div>}{status?.using_cache&&<div className="cache-note">{remoteBackend?`Snapshot data BPS per ${date(status.last_sync)}. Situs publik tidak memanggil API BPS.`:'Menampilkan data terakhir yang berhasil disinkronkan.'}{remoteBackend?'':status.stale?' Cache lebih dari 24 jam.':''} {status.error}</div>}</div>
  {(mode==='dashboard'||mode==='data')&&<section className="filters" aria-label="Filter data"><div className="filter-icon"><SlidersHorizontal size={18}/></div>{([['year','Tahun'],['category','Kategori'],['commodity','Komoditas'],['district','Kecamatan'],['unit','Satuan']] as const).map(([key,label])=><label key={key}>{label}<select value={filters[key]??''} onChange={e=>change(key,e.target.value)}><option value="">{key==='year'?'Terbaru':key==='unit'?'Pilih satuan':'Semua '+label.toLowerCase()}</option>{(options?.[key]??[]).map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}<button className="reset" onClick={()=>{setFilters({year:String(options?.defaults.year??''),unit:options?.defaults.unit??''});setPage(1);}}>Reset</button></section>}
  {loading&&mode!=='about'&&!(mode==='data'&&data)&&!(mode==='sources'&&tables.length)?<div className="skeleton-grid" aria-label="Memuat data"><div/><div/><div/><div/><div className="wide"/></div>:<>
  {mode==='dashboard'&&dashboard&&<><div className="section-kicker"><span>PRODUCTION OVERVIEW</span><span>{summary?.year??'—'} <b>·</b> {summary?.district_count??0} kecamatan dengan nilai tersedia</span></div><section className="kpis" aria-label="Indikator produksi"><article className="kpi featured"><div className="kpi-label">Total produksi <Leaf size={18}/></div><div className="kpi-value">{number(summary?.total)} <small>{unit}</small></div><div className="kpi-foot">Volume tercatat · satuan sejenis</div></article><article className="kpi"><div className="kpi-label">Komoditas terbesar <Sprout size={18}/></div><div className="kpi-value text-value">{top?.name??'—'}</div><div className="kpi-foot">{top&&summary?.total?number(top.value/summary.total*100,1)+'% dari produksi tercatat':'Belum ada data'}</div></article><article className="kpi"><div className="kpi-label">Kecamatan teratas <MapPin size={18}/></div><div className="kpi-value text-value">{district?.name??'—'}</div><div className="kpi-foot">{number(district?.value)} {unit} · {summary?.active_commodities??0} komoditas aktif</div></article><article className="kpi"><div className="kpi-label">Year-over-year <Activity size={18}/></div><div className={`kpi-value ${(summary?.yoy.change_percent??0)<0?'decline':'growth'}`}>{summary?.yoy.change_percent!=null&&(summary.yoy.change_percent<0?<ArrowDownRight size={25}/>:<ArrowUpRight size={25}/>)}{number(summary?.yoy.change_percent,2)}<small>%</small></div><div className="kpi-foot">{summary?.yoy.matched_observations??0} pasangan observasi · {Number(summary?.year)-1}</div></article></section>
  {summary?.message&&<div className="alert">{summary.message}</div>}<div className="chart-grid"><section className="panel"><div className="panel-heading"><div><h2>Production trend</h2><p>Pergerakan produksi antar tahun</p></div><span className="badge"><i/> {unit||'Tidak ada satuan'}</span></div>{dashboard.trends.series.length?<><TrendChart data={dashboard.trends.series} unit={unit}/><div className="chart-note">Total observasi tersedia; cakupan dapat berbeda antar tahun.</div><details className="accessible-data"><summary>Lihat angka grafik</summary><table><thead><tr><th>Tahun</th><th>Produksi ({unit})</th></tr></thead><tbody>{dashboard.trends.series.map(r=><tr key={r.year}><td>{r.year}</td><td>{number(r.value,2)}</td></tr>)}</tbody></table></details></>:<Empty/>}</section><section className="panel"><div className="panel-heading"><div><h2>Top commodities</h2><p>Lima komoditas dengan volume tertinggi</p></div><span className="tag">{summary?.year}</span></div>{summary?.top_commodities.length?<><RankChart data={summary.top_commodities.slice(0,5)} unit={unit}/><details className="accessible-data"><summary>Lihat angka peringkat</summary>{summary.top_commodities.slice(0,5).map(r=><p key={r.name}>{r.name}: {number(r.value,2)} {unit}</p>)}</details></>:<Empty/>}</section></div>
  <section className="insights-section"><div className="section-title"><div className="title-with-icon"><div className="section-icon"><Lightbulb size={21}/></div><div><h2>Agricultural insights</h2><p>Temuan dari data. Dengan bukti yang bisa ditelusuri.</p></div></div><span className="tag">RULE-BASED ANALYTICS</span></div><div className="insights-grid">{dashboard.insights.map((item,i)=><InsightCard item={item} key={i}/>)}</div>{!dashboard.insights.length&&<Empty text="Insight akan muncul saat observasi yang memadai tersedia."/>}</section>
  <div className="lower-grid"><section className="panel"><div className="panel-heading"><div><h2>Produksi menurut kecamatan</h2><p>Sentra produksi pada pilihan Anda</p></div><div className="segmented"><button aria-pressed={!allDistricts} onClick={()=>setAllDistricts(false)}>Top 10</button><button aria-pressed={allDistricts} onClick={()=>setAllDistricts(true)}>All</button></div></div>{summary?.top_districts.length?<><RankChart data={summary.top_districts.slice(0,allDistricts?undefined:10)} unit={unit} all/><details className="accessible-data"><summary>Lihat angka kecamatan</summary>{summary.top_districts.map(r=><p key={r.name}>{r.name}: {number(r.value,2)} {unit}</p>)}</details></>:<Empty/>}<p className="chart-note">Peringkat digunakan tanpa batas peta kecamatan yang belum terverifikasi.</p></section><section className="panel ml-panel"><div className="panel-heading"><div><span className="eyebrow">MACHINE LEARNING</span><h2>Pola kecamatan</h2></div><Layers3 size={23}/></div><p className="ml-intro">K-Means mengelompokkan kecamatan berdasarkan kemiripan karakteristik produksi, bukan batas administratif.</p>{dashboard.clusters.available?<><div className="ml-stats"><span><strong>{dashboard.clusters.k}</strong> clusters</span><span><strong>{number(dashboard.clusters.silhouette,3)}</strong> silhouette score</span></div><ClusterChart cluster={dashboard.clusters}/>{dashboard.clusters.clusters?.map(c=><details key={c.id} className="cluster-card"><summary>{c.name} · {c.districts.length} kecamatan</summary><p>{c.description}</p><p>{c.districts.join(', ')}</p><pre>{JSON.stringify(c.centroid,null,2)}</pre></details>)}<small>{dashboard.clusters.method}</small></>:<Empty text={`${dashboard.clusters.message} ${dashboard.clusters.eligible_districts??0} kecamatan memenuhi cakupan minimum. Pilih kategori untuk mengeksplorasi subset.`}/>}<div className="method-note"><ShieldCheck size={16}/><span>StandardScaler · k = 2–6 · Silhouette selection<br/>Cakupan ≥60%, minimal 6 kecamatan dan 2 anggota per cluster.</span></div></section></div><Sources items={summary?.provenance??[]}/></>}
  {mode==='data'&&<section className="panel explorer"><div className="panel-heading"><div><h2>Normalized observations</h2><p>{number(data?.total)} baris sesuai filter · nilai kosong ditampilkan sebagai —</p></div><a className="button" href={apiUrl(`/api/agriculture/data?${query}&search=${encodeURIComponent(search)}&sort=${sort}&direction=${direction}&export=csv`)}><Download size={15}/>Export CSV</a></div><div className="table-toolbar"><label className="search"><Search size={16}/><input aria-label="Cari kecamatan, komoditas, atau tabel" placeholder="Cari kecamatan, komoditas, tabel…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label>Urutkan <select aria-label="Kolom urutan" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}>{['year','district','commodity','indicator','value','unit'].map(k=><option key={k}>{k}</option>)}</select></label><button className="button" onClick={()=>setDirection(v=>v==='asc'?'desc':'asc')}>{direction==='asc'?'Ascending ↑':'Descending ↓'}</button></div><div className="table-scroll"><table><thead><tr>{['Year','Kecamatan','Commodity','Indicator','Value','Unit','Source'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data?.rows.map((r,i)=><tr key={i}><td>{r.year}</td><td>{r.district}</td><td>{r.commodity}</td><td>{r.indicator}</td><td className="numeric">{number(r.value,2)}</td><td>{r.unit??'—'}</td><td><details><summary>BPS <Info size={12}/></summary><p>{r.source_table_title}</p><small>{r.source_table_id} · Diakses {date(r.last_synced)}</small>{r.source_url&&<a className="source-link" href={r.source_url} target="_blank" rel="noreferrer">Buka tabel asli BPS ↗</a>}</details></td></tr>)}</tbody></table></div>{!data?.rows.length&&<Empty/>}<div className="pagination"><span>Halaman {page} dari {Math.max(1,Math.ceil((data?.total??0)/25))}</span><div><button className="button" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><button className="button" disabled={page*25 >= (data?.total??0)} onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div></div></section>}
  {mode==='sources'&&<><div className="source-hero"><ShieldCheck size={36}/><div><h2>Badan Pusat Statistik</h2><p>BPS Kabupaten Bogor · Official Data</p></div><a href="https://webapi.bps.go.id/documentation/" target="_blank" rel="noreferrer" className="button">API documentation <ExternalLink size={14}/></a></div><div className="source-codes"><div><span>PROVINCE</span><strong>3200</strong><p>Jawa Barat</p></div><div><span>LEGACY DOMAIN</span><strong>3201</strong><p>Kabupaten Bogor</p></div><div><span>SIMDASI WILAYAH</span><strong>3201000</strong><p>{status?.simdasi_connected?'Verified in successful synchronization':'Expected identifier · not verified'}</p></div></div><p className="terms-note">Konten dan layanan BPS dapat berubah atau ditarik. Data di sini merupakan salinan saat akses terakhir. <a href="https://www.bps.go.id/id/term-of-use" target="_blank" rel="noreferrer">Ketentuan konten BPS</a> · <a href="https://webapi.bps.go.id/developer/files/term_of_use.pdf" target="_blank" rel="noreferrer">Ketentuan API BPS</a></p><h2 className="list-title">Tabel yang digunakan <span>{tables.length}</span></h2><div className="source-list">{tables.map(t=><article className="panel" key={t.id}><span className="tag">{t.source} · {t.domain}</span><h3>{t.title}</h3><dl><div><dt>BPS table ID</dt><dd>{t.id}</dd></div><div><dt>Available years</dt><dd>{t.years.join(', ')||'Lihat metadata sumber'}</dd></div><div><dt>Ingested years</dt><dd>{t.ingested_years.join(', ')}</dd></div><div><dt>Units</dt><dd>{t.units.join(', ')}</dd></div><div><dt>Diakses / sinkronisasi</dt><dd>{date(t.last_sync)}</dd></div><div><dt>Penerbit</dt><dd>Badan Pusat Statistik</dd></div></dl>{t.source_url?<a className="source-link" href={t.source_url} target="_blank" rel="noreferrer">Buka tabel asli BPS ↗</a>:<p>Tautan langsung belum terverifikasi.</p>}</article>)}</div></>}
  {mode==='diagnostics'&&status&&<><div className="diagnostic-grid">{[['BPS authentication',status.api_key_configured?'Key configured; connection '+(status.api_connected?'verified this process':'not tested this process'):'Not configured'],['Domain discovery',status.bogor_domain_verified?'Verified: 3200 → 3201':'Not verified'],['SIMDASI availability',status.simdasi_connected?'Verified at last successful sync':'Not verified'],['Tables discovered',status.tables_discovered],['Agricultural tables selected',status.tables_selected],['Years available',String(status.quality.years??'—')],['Rows normalized',status.quality.rows_normalized??0],['Rows rejected',status.quality.rows_rejected??0],['Missing values',status.quality.missing_values??0],['Aggregate rows excluded',status.quality.aggregate_rows_excluded??0],['Unknown units',status.quality.unknown_units??0],['Last refresh',date(status.last_sync)]].map(([label,value])=><article className="panel" key={String(label)}><span className="eyebrow">{label}</span><h3>{typeof value==='number'?number(value):String(value)}</h3></article>)}</div><section className="panel"><h2>Pipeline messages</h2><p>{status.error??'Tidak ada kegagalan refresh tercatat.'}</p>{status.discovery_errors.map((e,i)=><p key={i}>{e}</p>)}<p>Nilai kosong dipertahankan. Baris total kabupaten dikeluarkan dari penjumlahan kecamatan. Skema yang tidak dikenali ditolak.</p></section></>}
  {mode==='about'&&<><section className="about-hero"><div className="eyebrow">PUBLIC DATA, MADE UNDERSTANDABLE</div><h2>A clearer view of<br/>Bogor&apos;s agriculture.</h2><p>Bogor Agricultural Intelligence is a data analytics platform designed to explore agricultural production patterns in Kabupaten Bogor using official statistical data from Badan Pusat Statistik.</p><Link className="button" href="/">Explore the dashboard <ArrowRight size={16}/></Link><Sprout className="about-leaf"/></section><section className="panel about-method"><h2>One transparent data journey</h2><div className="pipeline-diagram">{['Official BPS API','Discovery','Validation & cleaning','Normalized dataset','Statistical analytics','K-Means patterns','Explainable insights','Interactive UI'].map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong>{i<7&&<ArrowRight size={18}/>}</div>)}</div><h3>How to read the analysis</h3><p>Totals and rankings use observed production within one unit. They represent recorded volume, not economic value. YoY compares the same district–commodity observations across consecutive years. Trends require at least three years with a complete geographic panel.</p><p>K-Means standardizes available production features and compares k=2–6 using silhouette score. Sparse districts are excluded; missing features are median-imputed only when sufficient observations exist. Cluster labels describe measured centroids and have no inherent ordering.</p><p>Insights use deterministic rules and show their evidence. The largest percentage increase is separate from the largest absolute production. Growth insights require at least 1% of the prior observed total as a base and 80% pair coverage.</p><div className="alert">Data source: Badan Pusat Statistik (BPS). Analyses and derived insights are generated by this application and are not official BPS conclusions.</div></section></>}
  </>}
  <footer><span><Sprout size={14}/> Bogor Agricultural Intelligence</span><span>Source: BPS · Last synced {date(status?.last_sync)}</span></footer></main></div></div>;
}
